version: "3.7"

networks:
  proxy-network:
    external: "true"

secrets:
    default_email_address:
        file: ./secrets/default_email_address

services:
    nginx-reverse-proxy:
        image: "nginxproxy/nginx-proxy:latest"
        container_name: "nginx-reverse-proxy"
        volumes:
            - "html:/usr/share/nginx/html"
            - "vhost:/etc/nginx/vhost.d"
            - "certs:/etc/nginx/certs"
            - "/run/docker.sock:/tmp/docker.sock:ro"
            - "./custom_proxy.conf:/etc/nginx/conf.d/custom_proxy.conf:ro"
        restart: "always"
        ports:
            - 80:80
            - 443:443
        networks:
            - "proxy-network"

    letsencrypt:
        image: "nginxproxy/acme-companion:latest"
        container_name: "letsencrypt-helper"
        volumes:
            - "html:/usr/share/nginx/html"
            - "vhost:/etc/nginx/vhost.d"
            - "certs:/etc/nginx/certs"
            - "/run/docker.sock:/var/run/docker.sock:ro"
            - "acme:/etc/acme.sh"
        environment:
            NGINX_PROXY_CONTAINER: "nginx-reverse-proxy"
            DEFAULT_EMAIL: default_email_address
        restart: "always"
        depends_on:
            - "nginx-reverse-proxy"
        networks:
            - "proxy-network"
        secrets:
            - default_email_address
volumes:
  certs:
  html:
  vhost:
  acme: 

