version: "3.7"

volumes:
  blockstorage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/mnt/blockstorage/nextcloud"
  blockstorage_root1:
  nextcloud_db_vol:

networks:
  proxy-network:
    external: "true"

secrets:
  mysql_root_password: 
    file: ./secrets/mysql_root_password
  mysql_password:
    file: ./secrets/mysql_password
  mysql_database_name:
    file: ./secrets/mysql_database_name
  mysql_username:
    file: ./secrets/mysql_username
  mysql_hostname:
    file: ./secrets/mysql_hostname
  letsencrypt_email:
    file: ./secrets/letsencrypt_email

services:
  nextcloud_db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud_db_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mqsql_root_password
      MYSQL_PASSWORD: /run/secrets/mysql_password
      MYSQL_DATABASE: /run/secrets/mysql_database_name
      MYSQL_USER: /run/secrets/mysql_username
    networks:
      - "proxy-network"
    secrets:
      - mysql_root_password
      - mysql_password
      - mysql_database_name
      - mysql_username

  nextcloud:
    image: "nextcloud:24.0.1"
    container_name: "nextcloud"
    restart: "always"
    ports:
      - 3000:80
    links:
      - nextcloud_db
    volumes:
      - blockstorage:/var/www/html/data
    networks:
      - "proxy-network"
    environment:
      MYSQL_PASSWORD: /run/secrets/mysql_password
      MYSQL_DATABASE: /run/secrets/mysql_database_name
      MYSQL_USER: /run/secrets/mysql_username
      MYSQL_HOST: /run/secrets/mysql_hostname
      VIRTUAL_HOST: "nextcloud.shivamnaik.de"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "nextcloud.shivamnaik.de"
      LETSENCRYPT_EMAIL: "ichbinshivamsnaik@outlook.com"
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.shivamnaik.de"
      NEXTCLOUD_DATA_DIR: /var/www/html/data
      OVERWRITEPROTOCOL: https
      OVERWRITECLIURL: https://nextcloud.shivamnaik.de
    
    secrets:
      - mysql_password
      - mysql_database_name
      - mysql_username
      - mysql_hostname
      - letsencrypt_email

  
